#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (C) 2016-2017 Niccolo Rigacci <niccolo@rigacci.org>

# Save AirPi sensors data to permanent storage, run as cronjob.
#
# Read the following sensors:
#   * PMS5003 Particulate Matter
#   * BME280 Barometric, Temperature, Humidity
# Write to the following storages (via external scripts):
#   * SQLite database
#   * RRD archive

import datetime, logging, os.path, subprocess, sys, time

# Status file containing the data acquired by PMS5003,
# it contains: timestamp data1 data2 data3 ...
PMS5003_STATUS = '/var/run/pms5003.status'
# MAX_AGE (seconds) of timestamp: print an error if data is older than this.
# It should be greather than the acquiring interval, but less than twice such interval.
MAX_AGE = 18 * 60

# Data read from status file is in this order.
PMS5003_DATA = ['cf1pm1.0', 'cf1pm2.5', 'cf1pm10', 'pm1.0', 'pm2.5', 'pm10', 'gt0.3um', 'gt0.5um', 'gt1.0um', 'gt2.5um', 'gt5um', 'gt10um']
# Data read from BME280 sensor.
BME280_DATA = ['t', 'p', 'hum']

# Where are the utility scripts.
LIB_DIR = '/usr/local/lib/airpi'

NAME = os.path.basename(sys.argv[0])

#----------------------------------------------------------------
# Fill this dictionary with sensor data.
#----------------------------------------------------------------
values = {}

#----------------------------------------------------------------
# Get PMS5003 sensor data (read status file).
#----------------------------------------------------------------
try:
    fp = open(PMS5003_STATUS, "r")
    data = fp.readline().strip().split(" ")
    fp.close()
except Exception, e:
    logging.error(u'%s: Reading PMS5003 status file: %s' % (NAME, str(e)))

try:
    i = 0
    timestamp = datetime.datetime.strptime(data[i], "%Y-%m-%dT%H:%M:%SZ")
    data_age = (datetime.datetime.utcnow() - timestamp).seconds
    if data_age > MAX_AGE:
        logging.warning(u'%s: PMS5003 status file contains old data' % (NAME,))
    else:
        for key in PMS5003_DATA:
            i += 1
            values[key] = "%0.3f" % (float(data[i]))
except Exception, e:
    logging.error(u'%s: Parsing PMS5003 status file: %s' % (NAME, str(e)))

#----------------------------------------------------------------
# Get BME280 sensor data (exec program and read output).
#----------------------------------------------------------------
try:
    cmd = [os.path.join(LIB_DIR, 'bme280-snmp')]
    subproc = subprocess.Popen(cmd, stdin=None, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, stderr = subproc.communicate()
    retcode = subproc.returncode
except Exception, e:
    logging.error(u'%s: Failed to exec BME280 read program: %s' % (NAME, str(e)))
    retcode = -1

if retcode == 0:
    for line in output.splitlines():
        if line.startswith('Temperature'):
            values['t'] = "%0.2f" % (float(line.split(':')[1]))
        elif line.startswith('Pressure'):
            values['p'] = "%0.2f" % (float(line.split(':')[1]))
        elif line.startswith('Humidity'):
            values['hum'] = "%0.2f" % (float(line.split(':')[1]))
else:
    logging.error(u'%s: Cannot read values from BME280' % (NAME,))

#----------------------------------------------------------------
# Timestamp: seconds since Unix epoch and UTC timestamp string.
#----------------------------------------------------------------
time_now = int(time.time())
timestamp_utc_now = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime(time_now))

#----------------------------------------------------------------
# Store data values into the RRD archive.
#----------------------------------------------------------------
# Template which specifies what data sources and in what order.
template = ':'.join(BME280_DATA + PMS5003_DATA).replace('.', '_')
data = []
for key in (BME280_DATA + PMS5003_DATA):
    if key in values.keys():
        data.append(values[key])
    else:
        data.append('U')
cmd = [os.path.join(LIB_DIR, 'airpi-rrdtool-update'), str(time_now), '0', template, ':'.join(data)]
#print cmd
retcode = subprocess.call(cmd)
if retcode != 0:
    logging.error(u'%s: Storing sensors data into RRD archive failed' % (NAME,))

#----------------------------------------------------------------
# Store data values into the SQLite database.
#----------------------------------------------------------------
if len(values) > 0:
    data = []
    for key, val in values.iteritems():
        data.append("%s=%s" % (key, val))
    cmd = [os.path.join(LIB_DIR, 'airpi-sql-insert'), timestamp_utc_now, ','.join(data)]
    #print cmd
    retcode = subprocess.call(cmd)
    if retcode != 0:
        logging.error(u'%s: Storing sensors data into SQL database failed' % (NAME,))
