#!/bin/sh

# Read configuration file.
MQTT_HOST="$(grep '^MQTT_HOST\s*=' /etc/airpi/airpi.cfg | sed 's/^[^=]\+=\s*//')"
MQTT_LOGIN="$(grep '^MQTT_LOGIN\s*=' /etc/airpi/airpi.cfg | sed 's/^[^=]\+=\s*//')"
MQTT_PASSWORD="$(grep '^MQTT_PASSWORD\s*=' /etc/airpi/airpi.cfg | sed 's/^[^=]\+=\s*//')"

# MQTT client options.
MQTT_OPTIONS="-h $MQTT_HOST -t outSensorTopic -u $MQTT_LOGIN -P $MQTT_PASSWORD"
# MQTT message format: -m "id;pm2.5;pm10;[timestamp]"

DATA="$(rrdtool lastupdate /var/lib/airpi/airpi-data-0.rrd | tail -n1)"
# Example output:
# t p hum cf1pm1_0 cf1pm2_5 cf1pm10 pm1_0 pm2_5 pm10 gt0_3um gt0_5um gt1_0um gt2_5um gt5um gt10um
#
# 1486565705: 13050 1008300 55060 4 7 8 4 7 8 982 224 23 3 1 0

timestamp="$(echo "$DATA" | cut -f1 -d:)"
pm25="$(echo "$DATA" | cut -f9  -d' ')"
pm10="$(echo "$DATA" | cut -f10 -d' ')"
now="$(date +%s)"
age="$(($now - $timestamp))"

if [ "$age" -lt 600 ]; then
    mosquitto_pub $MQTT_OPTIONS -m "${MQTT_LOGIN};${pm25};${pm10};${timestamp}000"
    exit $?
else
    echo "ERROR: Last update in RRD archive is too old: $now - $timestamp = $age"
    exit 1
fi
