#!/bin/sh -e

# Control the GPIO pin connected to the PMS5003 sensor RESET line.
# Normally HIGH, set it to LOW for a short time to reset.

N=17
GPIO="/sys/class/gpio/gpio${N}"

# Export the GPIO and set its direction to output.
# Leave the GPIO exported, otherwise direction and state are lost.
test -d "$GPIO" || (echo "$N" > '/sys/class/gpio/export'; sleep 0.2)
test "$(cat ${GPIO}/direction)" = 'out' || (echo out > "${GPIO}/direction"; sleep 0.2)

case "$1" in
    high)
        echo 1 > ${GPIO}/value
        ;;
    low)
        echo 0 > ${GPIO}/value
        ;;
    reset)
        if [ "$(cat ${GPIO}/value)" != '1' ]; then
            echo 1 > ${GPIO}/value
            sleep 0.5
        fi
        echo 0 > ${GPIO}/value
        sleep 0.5
        echo 1 > ${GPIO}/value
        ;;
    *)
        echo "Usage: $(basename $0) {high|low|reset}"
        exit 1
        ;;
esac
