#!/bin/sh

RRD_ARCHVIE='/var/lib/airpi/airpi-data.rrd'
TIMESTAMP="$(/bin/date '+%Y-%m-%d %H:%M')"

case "$1" in
    daily)
        START='-86400'
        AVG='5 min'
        ;;
    monthly)
        START='-2678400'
        AVG='2 hours'
        ;;
    yearly)
        START='-31622400'
        AVG='1 day'
        ;;
    *)
        START='-604800'
        AVG='30 min'
        ;;
esac

/usr/bin/rrdtool graph - \
--imgformat=PNG \
--start="$START" \
--end='-300' \
--title="Air Particle Count, $AVG avg. ($TIMESTAMP)" \
--base='1000' \
--height='240' \
--width='640' \
--alt-autoscale-max \
--lower-limit='0' \
--vertical-label='Count' \
--slope-mode \
--font TITLE:10: \
--font AXIS:7: \
--font LEGEND:8: \
--font UNIT:7: \
DEF:a="$RRD_ARCHVIE":gt0_3um:AVERAGE \
DEF:b="$RRD_ARCHVIE":gt0_5um:AVERAGE \
DEF:c="$RRD_ARCHVIE":gt1_0um:AVERAGE \
DEF:d="$RRD_ARCHVIE":gt2_5um:AVERAGE \
DEF:e="$RRD_ARCHVIE":gt5um:AVERAGE \
AREA:a#e1c696FF:'> 0.3 um'  \
GPRINT:a:LAST:'Cur\:%8.0lf'  \
GPRINT:a:AVERAGE:'Avg\:%8.0lf'  \
GPRINT:a:MAX:'Max\:%8.0lf\n'  \
AREA:b#ba9b64FF:'> 0.5 um'  \
GPRINT:b:LAST:'Cur\:%8.0lf'  \
GPRINT:b:AVERAGE:'Avg\:%8.0lf'  \
GPRINT:b:MAX:'Max\:%8.0lf\n'  \
AREA:c#8e7448FF:'> 1.0 um'  \
GPRINT:c:LAST:'Cur\:%8.0lf'  \
GPRINT:c:AVERAGE:'Avg\:%8.0lf'  \
GPRINT:c:MAX:'Max\:%8.0lf\n'  \
AREA:d#A150AAFF:'> 2.5 um'  \
GPRINT:d:LAST:'Cur\:%8.0lf'  \
GPRINT:d:AVERAGE:'Avg\:%8.0lf'  \
GPRINT:d:MAX:'Max\:%8.0lf\n'  \
AREA:e#B90054FF:'> 5.0 um'  \
GPRINT:e:LAST:'Cur\:%8.0lf'  \
GPRINT:e:AVERAGE:'Avg\:%8.0lf'  \
GPRINT:e:MAX:'Max\:%8.0lf\n' 
